[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt",
    "pip install whitenoise==6.7.0 --force-reinstall"
]

[phases.start]
cmds = ["python manage.py migrate && gunicorn videoChat.wsgi --bind 0.0.0.0:$PORT --workers 4"]